name: rces
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - xarray
  - cartopy
  - netcdf4
  - dask
  - jupyter
  - jupyterlab
  - xarray=0.12.3
  - scipy
  - proj4
  - pyresample
  - pandas
  
               
